version: '3.8'
services:
  db:
    build:
      context: .
      dockerfile: dockerfile.db
    platform: linux/amd64
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: omena222
      MYSQL_DATABASE: grifo
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    restart: always
    networks:
      - app-network

  app:
    build:
      context: ./grifoBack
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: root
      DATABASE_PASSWORD: omena222
      DATABASE_NAME: grifo
    networks:
      - app-network

  frontend:
    build:
      context: ./grifoFront
      dockerfile: dockerfile.frontend
    ports:
      - "4173:4173"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:

